name: Deploy static site

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Inspect repository contents
        run: |
          set -euxo pipefail
          pwd
          ls -al
          find . -maxdepth 2 -type f

      - name: Verify required files
        run: |
          set -euxo pipefail
          paths=(
            "index.html"
            "styles.css"
            "script.js"
            "amenities.html"
            "gallery.html"
            "inquire.html"
            "location.html"
            "residences.html"
            "img/hero.jpg"
            "img/interior-1.jpg"
            "img/interior-2.jpg"
            "img/interior-3.jpg"
            "img/interior-4.jpg"
          )
          for p in "${paths[@]}"; do
            if [ ! -e "$p" ]; then
              echo "::error::Required file missing: $p"
              exit 1
            fi
            ls -l "$p"
          done

      - name: Prepare static bundle
        run: |
          set -euxo pipefail
          rm -rf dist
          mkdir dist
          rsync -av \
            --exclude '.git/' \
            --exclude '.github/' \
            --exclude 'venv/' \
            --exclude '*.md' \
            --exclude 'requirements.txt' \
            ./ dist/
          ls -al dist

      - name: Upload static site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
